// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFIq9TQJ0OQlBdKirVuA1tdQmg3cvixsw',
    appId: '1:81173432041:android:2f61c0a6e217299b18d278',
    messagingSenderId: '81173432041',
    projectId: 'budget-buddy-35521',
    storageBucket: 'budget-buddy-35521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyQn70B8VN3Xu3mSG2qgvUv8nH4jj2nzQ',
    appId: '1:81173432041:ios:ea99923775785c0018d278',
    messagingSenderId: '81173432041',
    projectId: 'budget-buddy-35521',
    storageBucket: 'budget-buddy-35521.firebasestorage.app',
    androidClientId: '81173432041-7lin8slc0pc6ss6tlvph49ecdu13gaob.apps.googleusercontent.com',
    iosClientId: '81173432041-qtd0pa99b7riegostg1484qpicii7bpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetBuddy',
  );
}
