// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkN69V-WHXp2BH_jmFMYV5sJlkRknR9QA',
    appId: '1:28884617565:android:f59d6f0731151d592ac0b4',
    messagingSenderId: '28884617565',
    projectId: 'budget-buddy-94cd2',
    storageBucket: 'budget-buddy-94cd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5eRx6gc0GYTaekI1G3UJUEjYPRV4qLHI',
    appId: '1:28884617565:ios:1466f7eb7c31170b2ac0b4',
    messagingSenderId: '28884617565',
    projectId: 'budget-buddy-94cd2',
    storageBucket: 'budget-buddy-94cd2.firebasestorage.app',
    iosBundleId: 'com.example.budgetbuddyClient',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPL_E1letDf3p3FiEnzFPUhwzr4188IbA',
    appId: '1:28884617565:web:9d2b4f33ec9d9b5f2ac0b4',
    messagingSenderId: '28884617565',
    projectId: 'budget-buddy-94cd2',
    authDomain: 'budget-buddy-94cd2.firebaseapp.com',
    storageBucket: 'budget-buddy-94cd2.firebasestorage.app',
    measurementId: 'G-F3S6WC2S8P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5eRx6gc0GYTaekI1G3UJUEjYPRV4qLHI',
    appId: '1:28884617565:ios:1466f7eb7c31170b2ac0b4',
    messagingSenderId: '28884617565',
    projectId: 'budget-buddy-94cd2',
    storageBucket: 'budget-buddy-94cd2.firebasestorage.app',
    iosBundleId: 'com.example.budgetbuddyClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPL_E1letDf3p3FiEnzFPUhwzr4188IbA',
    appId: '1:28884617565:web:7c6d2294a716b6a42ac0b4',
    messagingSenderId: '28884617565',
    projectId: 'budget-buddy-94cd2',
    authDomain: 'budget-buddy-94cd2.firebaseapp.com',
    storageBucket: 'budget-buddy-94cd2.firebasestorage.app',
    measurementId: 'G-HS0E9ZN7WV',
  );

}